### ISSUE TITLE
pip install celi-framework==0.0.16 not working

### ISSUE THREAD

**Issue by x3n0cr4735** [x3n0cr4735/celi#30]
(celi-0.0.15) jwag@Jan-Samuels-MacBook-Pro test_celi % python -m celi_framework.main
2024-04-20 06:55:18,061 __main__ DEBUG - Starting CELI
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/jwag/anaconda3/envs/celi-0.0.15/lib/python3.11/site-packages/celi_framework/main.py", line 166, in <module>
    config = get_config()
             ^^^^^^^^^^^^
  File "/Users/jwag/anaconda3/envs/celi-0.0.15/lib/python3.11/site-packages/celi_framework/main.py", line 131, in get_config
    tool_implementations = job_description.tool_implementations_class(**tool_config)
                                                                        ^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'tool_config' where it is not associated with a value

.env:

OPENAI_API_KEY=<KEY>
OUTPUT_DIR=target/celi_output
DB_URL=mongodb://localhost:27017/
EXTERNAL_DB=True
NO_MONITOR=True
JOB_DESCRIPTION=celi_framework.examples.wikipedia.job_description.job_description
TOOL_CONFIG_JSON=celi_framework/examples/wikipedia/example_config.json
PARSER_MODEL_CLASS=llm_core.parsers.OpenAIParser
PARSER_MODEL_NAME=gpt-3.5-turbo-16k

**Comment by DaveDeCaprio** [comment]
I created a PR to fix that, but there is still something wrong with your setup.

Is your .env file in the directory where you are running python from?  The only way I can replicate your error is by removing my .env file.

I added logging so it prints out the environment variable now.  That should help clarify.

**Comment by x3n0cr4735** [comment]
Merged your changed. Deployed as v0.0.17.

new anaconda env
pip install celi-framework

conda list:
celi-framework            0.0.17                   pypi_0    pypi

mkdir test_celi
cd test_celi

nano .env:

OPENAI_API_KEY=<KEY>
OUTPUT_DIR=target/celi_output
DB_URL=mongodb://localhost:27017/
EXTERNAL_DB=True
NO_MONITOR=True
JOB_DESCRIPTION=celi_framework.examples.wikipedia.job_description.job_description
TOOL_CONFIG_JSON=celi_framework/examples/wikipedia/example_config.json
PARSER_MODEL_CLASS=llm_core.parsers.OpenAIParser
PARSER_MODEL_NAME=gpt-3.5-turbo-16k

python -m celi_framework.main

(celi-0.0.17) jwag@Jan-Samuels-MacBook-Pro test_celi % python -m celi_framework.main
2024-04-21 08:34:48,803 __main__ DEBUG - Starting CELI
2024-04-21 08:34:48,803 __main__ INFO - Tool config env. var is <not set>
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/jwag/anaconda3/envs/celi-0.0.17/lib/python3.11/site-packages/celi_framework/main.py", line 167, in <module>
    config = get_config()
             ^^^^^^^^^^^^
  File "/Users/jwag/anaconda3/envs/celi-0.0.17/lib/python3.11/site-packages/celi_framework/main.py", line 132, in get_config
    tool_implementations = job_description.tool_implementations_class(**tool_config)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: WikipediaToolImplementations.__init__() missing 2 required positional arguments: 'example_url' and 'target_url'

**Comment by x3n0cr4735** [comment]
Merged your changed. Deployed as v0.0.17.

new anaconda env
pip install celi-framework

conda list:
celi-framework 0.0.17 pypi_0 pypi

mkdir test_celi
cd test_celi

nano .env:

OPENAI_API_KEY=
OUTPUT_DIR=target/celi_output
DB_URL=mongodb://localhost:27017/
EXTERNAL_DB=True
NO_MONITOR=True
JOB_DESCRIPTION=celi_framework.examples.wikipedia.job_description.job_description
TOOL_CONFIG_JSON=celi_framework/examples/wikipedia/example_config.json
PARSER_MODEL_CLASS=llm_core.parsers.OpenAIParser
PARSER_MODEL_NAME=gpt-3.5-turbo-16k

python -m celi_framework.main

(celi-0.0.17) jwag@Jan-Samuels-MacBook-Pro test_celi % python -m celi_framework.main
2024-04-21 08:34:48,803 main DEBUG - Starting CELI
2024-04-21 08:34:48,803 main INFO - Tool config env. var is **<not set>**
Traceback (most recent call last):
File "", line 198, in _run_module_as_main
File "", line 88, in _run_code
File "/Users/jwag/anaconda3/envs/celi-0.0.17/lib/python3.11/site-packages/celi_framework/main.py", line 167, in
config = get_config()
^^^^^^^^^^^^
File "/Users/jwag/anaconda3/envs/celi-0.0.17/lib/python3.11/site-packages/celi_framework/main.py", line 132, in get_config
tool_implementations = job_description.tool_implementations_class(**tool_config)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: WikipediaToolImplementations.init() missing 2 required positional arguments: 'example_url' and 'target_url'

**Comment by x3n0cr4735** [comment]
<img width="525" alt="Screenshot 2024-04-21 at 8 47 35 AM" src="https://github.com/x3n0cr4735/celi/assets/16089135/af842ed3-5082-4d6c-a309-c853a6a5bb14">

**Comment by DaveDeCaprio** [comment]
Ok, figured it out.  This was a bit tricky.

When running python with -m, load_dotenv DOESN'T search your current working directory.  
If there is a __main__ module (which is what happens when you run a script or from Jupyter), then it does use the current dir.
If there is no __maim__ module (which happens with -m, the module is loaded as celi_framework_main and not __main__), it finds the root of the current stack trace and then searches up in the directory hierarchy from there.

This works if you put your venv inside your current directory (which I do by default), but doesn't if your venv is not.  That's why you were having issues.

The fix is just to tell load_dotenv in celi_framework.main to always use the cwd.

**Comment by x3n0cr4735** [comment]
Hey Dave since you'll have OS X to test I'll approve code reviews and then you can just merge, deploy and test off pip install.
