### ISSUE TITLE
Pypi badge is outdated

### ISSUE THREAD

**Issue by x3n0cr4735** [x3n0cr4735/celi#39]
For some reason the pypi badge on the READM is not getting updated with releases. Same for PyPi page. But different versions showing on both

**Comment by DaveDeCaprio** [comment]
It all looks correct, and this is showing the right version: https://badge.fury.io/for/py/celi-framework

 

I also tried changing the readme just to see if it was caching, but it doesn’t seem to be.

 

I’d give it a couple days and see if it catches up.  It could be some other caching problem.

 

Dave

 

From: Jan-Samuel Wagner ***@***.***> 
Sent: Sunday, April 21, 2024 10:41 AM
To: x3n0cr4735/celi ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [x3n0cr4735/celi] Pypi badge is outdated (Issue #39)

 

For some reason the pypi badge on the READM is not getting updated with releases. Same for PyPi page. But different versions showing on both

**Comment by x3n0cr4735** [comment]
Works. It's just taking a day to see sync.
