### ISSUE TITLE
running wikipedia example from source (with poetry) not working

### ISSUE THREAD

**Issue by x3n0cr4735** [x3n0cr4735/celi#44]
(celi-framework-py3.11) (base) jwag@Jan-Samuels-MacBook-Pro celi % python -m celi_framework.main
2024-04-25 10:52:56,916 __main__ DEBUG - Starting CELI
2024-04-25 10:52:56,917 __main__ INFO - Tool config env. var is celi_framework/examples/wikipedia/example_config.json
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/jwag/PycharmProjects/celi/celi_framework/main.py", line 167, in <module>
    config = get_config()
             ^^^^^^^^^^^^
  File "/Users/jwag/PycharmProjects/celi/celi_framework/main.py", line 113, in get_config
    job_description = get_obj_by_name(args.job_description)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jwag/PycharmProjects/celi/celi_framework/utils/utils.py", line 52, in get_obj_by_name
    module = importlib.import_module(module_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jwag/anaconda3/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/jwag/PycharmProjects/celi/celi_framework/examples/wikipedia/job_description.py", line 3, in <module>
    from celi_framework.examples.wikipedia.tools import WikipediaToolImplementations
  File "/Users/jwag/PycharmProjects/celi/celi_framework/examples/wikipedia/tools.py", line 10, in <module>
    from llama_index.vector_stores.chroma.base import ChromaVectorStore
  File "/Users/jwag/PycharmProjects/celi/.venv/lib/python3.11/site-packages/llama_index/vector_stores/chroma/__init__.py", line 1, in <module>
    from llama_index.vector_stores.chroma.base import ChromaVectorStore
  File "/Users/jwag/PycharmProjects/celi/.venv/lib/python3.11/site-packages/llama_index/vector_stores/chroma/base.py", line 7, in <module>
    import chromadb
  File "/Users/jwag/PycharmProjects/celi/.venv/lib/python3.11/site-packages/chromadb/__init__.py", line 5, in <module>
    from chromadb.auth.token import TokenTransportHeader
  File "/Users/jwag/PycharmProjects/celi/.venv/lib/python3.11/site-packages/chromadb/auth/token/__init__.py", line 26, in <module>
    from chromadb.telemetry.opentelemetry import (
  File "/Users/jwag/PycharmProjects/celi/.venv/lib/python3.11/site-packages/chromadb/telemetry/opentelemetry/__init__.py", line 11, in <module>
    from opentelemetry.exporter.otlp.proto.grpc.trace_exporter import OTLPSpanExporter
  File "/Users/jwag/PycharmProjects/celi/.venv/lib/python3.11/site-packages/opentelemetry/exporter/otlp/proto/grpc/trace_exporter/__init__.py", line 22, in <module>
    from opentelemetry.exporter.otlp.proto.grpc.exporter import (
  File "/Users/jwag/PycharmProjects/celi/.venv/lib/python3.11/site-packages/opentelemetry/exporter/otlp/proto/grpc/exporter.py", line 39, in <module>
    from opentelemetry.proto.common.v1.common_pb2 import (
  File "/Users/jwag/PycharmProjects/celi/.venv/lib/python3.11/site-packages/opentelemetry/proto/common/v1/common_pb2.py", line 36, in <module>
    _descriptor.FieldDescriptor(
  File "/Users/jwag/PycharmProjects/celi/.venv/lib/python3.11/site-packages/google/protobuf/descriptor.py", line 621, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

**Comment by DaveDeCaprio** [comment]
@x3n0cr4735 Can you run `pip list` and paste the result here.  That will help me narrow down what the issue is.

**Comment by x3n0cr4735** [comment]
Package                                 Version     Editable project location
--------------------------------------- ----------- --------------------------------
aiohttp                                 3.9.3
aiosignal                               1.3.1
alabaster                               0.7.16
annotated-types                         0.6.0
anyio                                   4.3.0
appnope                                 0.1.4
asgiref                                 3.8.1
asttokens                               2.4.1
attrs                                   23.2.0
Babel                                   2.14.0
backoff                                 1.11.1
bcrypt                                  4.1.2
beautifulsoup4                          4.12.3
bert-score                              0.3.13
build                                   1.2.1
cachetools                              5.3.3
cattrs                                  23.2.3
celi-framework                          0.0.10      /Users/jwag/PycharmProjects/celi
certifi                                 2024.2.2
cffi                                    1.16.0
charset-normalizer                      3.3.2
chroma-hnswlib                          0.7.3
chromadb                                0.4.24
click                                   8.1.7
colorama                                0.4.6
coloredlogs                             15.0.1
comm                                    0.2.2
contourpy                               1.2.1
cycler                                  0.12.1
dataclasses-json                        0.6.4
datasets                                2.18.0
debugpy                                 1.8.1
decorator                               5.1.1
Deprecated                              1.2.14
dill                                    0.3.8
dirtyjson                               1.0.8
diskcache                               5.6.3
distro                                  1.9.0
dnspython                               2.6.1
docutils                                0.20.1
evaluate                                0.4.1
executing                               2.0.1
fastapi                                 0.110.1
filelock                                3.13.4
flatbuffers                             24.3.25
fonttools                               4.51.0
frozenlist                              1.4.1
fsspec                                  2024.2.0
furo                                    2023.9.10
google-auth                             2.29.0
googleapis-common-protos                1.56.1
greenlet                                3.0.3
grpcio                                  1.62.1
h11                                     0.14.0
httpcore                                1.0.5
httptools                               0.6.1
httpx                                   0.27.0
huggingface-hub                         0.22.2
humanfriendly                           10.0
idna                                    3.6
imagesize                               1.4.1
importlib-metadata                      7.0.0
importlib_resources                     6.4.0
iniconfig                               2.0.0
ipykernel                               6.29.4
ipython                                 8.23.0
jedi                                    0.19.1
Jinja2                                  3.1.3
joblib                                  1.4.0
jsonschema                              4.21.1
jsonschema-specifications               2023.12.1
jupyter_client                          8.6.1
jupyter_core                            5.7.2
kiwisolver                              1.4.5
kubernetes                              29.0.0
livereload                              2.6.3
llama_cpp_python                        0.2.61
llama-index                             0.10.28
llama-index-agent-openai                0.2.2
llama-index-cli                         0.1.11
llama-index-core                        0.10.28
llama-index-embeddings-openai           0.1.7
llama-index-indices-managed-llama-cloud 0.1.5
llama-index-legacy                      0.9.48
llama-index-llms-openai                 0.1.15
llama-index-multi-modal-llms-openai     0.1.5
llama-index-program-openai              0.1.5
llama-index-question-gen-openai         0.1.3
llama-index-readers-file                0.1.16
llama-index-readers-llama-parse         0.1.4
llama-index-vector-stores-chroma        0.1.6
llama-parse                             0.4.0
llamaindex-py-client                    0.1.16
lxml                                    5.2.1
markdown-it-py                          3.0.0
MarkupSafe                              2.1.5
marshmallow                             3.21.1
matplotlib                              3.8.4
matplotlib-inline                       0.1.6
mdit-py-plugins                         0.4.0
mdurl                                   0.1.2
mmh3                                    4.1.0
monotonic                               1.6
mpmath                                  1.3.0
multidict                               6.0.5
multiprocess                            0.70.16
mypy-extensions                         1.0.0
myst-parser                             2.0.0
nest-asyncio                            1.6.0
networkx                                3.3
nltk                                    3.8.1
numpy                                   1.26.4
oauthlib                                3.2.2
onnxruntime                             1.17.1
openai                                  1.16.2
opentelemetry-api                       1.24.0
opentelemetry-exporter-otlp-proto-grpc  1.11.1
opentelemetry-instrumentation           0.45b0
opentelemetry-instrumentation-asgi      0.45b0
opentelemetry-instrumentation-fastapi   0.45b0
opentelemetry-proto                     1.11.1
opentelemetry-sdk                       1.24.0
opentelemetry-semantic-conventions      0.45b0
opentelemetry-util-http                 0.45b0
orjson                                  3.10.0
overrides                               7.7.0
packaging                               24.0
pandas                                  2.2.1
parso                                   0.8.4
pexpect                                 4.9.0
pillow                                  10.3.0
pip                                     24.0
platformdirs                            4.2.0
pluggy                                  1.4.0
posthog                                 3.5.0
prompt-toolkit                          3.0.43
protobuf                                5.26.1
psutil                                  5.9.8
ptyprocess                              0.7.0
pulsar-client                           3.4.0
pure-eval                               0.2.2
py-llm-core                             2.8.2
pyarrow                                 15.0.2
pyarrow-hotfix                          0.6
pyasn1                                  0.6.0
pyasn1_modules                          0.4.0
pycparser                               2.22
pydantic                                2.6.4
pydantic_core                           2.16.3
Pygments                                2.17.2
pymongo                                 4.6.3
PyMuPDF                                 1.24.1
PyMuPDFb                                1.24.1
pyparsing                               3.1.2
pypdf                                   4.2.0
PyPika                                  0.48.9
pyproject_hooks                         1.0.0
pytest                                  8.1.1
pytest-asyncio                          0.23.6
python-dateutil                         2.9.0.post0
python-decouple                         3.8
python-docx                             1.1.0
python-dotenv                           1.0.1
pytz                                    2024.1
PyYAML                                  6.0.1
pyzmq                                   25.1.2
referencing                             0.34.0
regex                                   2023.12.25
requests                                2.31.0
requests-cache                          1.2.0
requests-oauthlib                       2.0.0
responses                               0.18.0
rich                                    13.7.1
rpds-py                                 0.18.0
rsa                                     4.9
safetensors                             0.4.2
scikit-learn                            1.4.2
scipy                                   1.13.0
setuptools                              69.2.0
shellingham                             1.5.4
six                                     1.16.0
sniffio                                 1.3.1
snowballstemmer                         2.2.0
soupsieve                               2.5
Sphinx                                  7.2.6
sphinx-autobuild                        2021.3.14
sphinx-autodoc-typehints                2.0.0
sphinx-basic-ng                         1.0.0b2
sphinx-copybutton                       0.5.2
sphinxcontrib-applehelp                 1.0.8
sphinxcontrib-devhelp                   1.0.6
sphinxcontrib-htmlhelp                  2.0.5
sphinxcontrib-jsmath                    1.0.1
sphinxcontrib-qthelp                    1.0.7
sphinxcontrib-serializinghtml           1.1.10
sphinxext-opengraph                     0.9.1
SQLAlchemy                              2.0.29
stack-data                              0.6.3
starlette                               0.37.2
striprtf                                0.0.26
sympy                                   1.12
tenacity                                8.2.3
threadpoolctl                           3.4.0
tiktoken                                0.6.0
tokenizers                              0.15.2
torch                                   2.2.2
tornado                                 6.4
tqdm                                    4.66.2
traitlets                               5.14.2
transformers                            4.39.3
typer                                   0.12.3
typing_extensions                       4.11.0
typing-inspect                          0.9.0
tzdata                                  2024.1
url-normalize                           1.4.3
urllib3                                 2.2.1
uvicorn                                 0.29.0
uvloop                                  0.19.0
watchfiles                              0.21.0
wcwidth                                 0.2.13
websocket-client                        1.7.0
websockets                              12.0
wrapt                                   1.16.0
xxhash                                  3.4.1
yarl                                    1.9.4
zipp                                    3.18.1

**Comment by DaveDeCaprio** [comment]
Actually, I was able to replicate it.  I'm good.

**Comment by x3n0cr4735** [comment]
cool
