### ISSUE TITLE
Future: choose to use non-default LLM model within task

### ISSUE THREAD

**Issue by x3n0cr4735** [x3n0cr4735/celi#51]
For future, but wanted to put this on our radar

**Comment by x3n0cr4735** [comment]
change models between tasks to be more specific

**Comment by DaveDeCaprio** [comment]
The Celi Processor doesn't explicitly track what task you are on, that's all within the LLM prompt.

If you let me know what the use case is where you need this, we can try to figure out how to accomplish what you want.  We already have the ability to have specific tools that use different LLMs than the main one.  We could support a built-in tool that allows you to choose a different LLM for the main processor,  I don't know if that would accomplish what you are looking for.

**Comment by x3n0cr4735** [comment]
This would be for when you want to send the entire context (system and user message) to a different model than the one that was used to develop the context. 

One use case would be that we want to use a 16k or 32k context model until the context grows too large and we need to send the entire context to a new model.

**Comment by x3n0cr4735** [comment]
Like what if we want use open source models until the context gets too large or complex and want to flip it over to 4o.
